### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JamiKettunen** [arch-installer/setup#1]
**Script**
- [x] Add "Back" option to mounting menu
- [ ] Make installer script UI localizable
- [ ] Add dynamic progress messages e.g. for pacman & pacstrap

**Add**
- [ ] Web server stack setup (LEMP / LAMP)
- [ ] ALSA setup without pulseaudio

**Improvements**
- [ ] Pre-built used AUR packages to speed up setup process dramatically
- [x] AMD GPU drivers setup
- [ ] Power saving features
- [ ] Assistive techologies setup
- [ ] Post-install boot time improvements?
- [ ] Add all other TODOs here...

**Disks**
- [ ] Allow unmounting by choosing a mount again & run `umount -R ...`
- [ ] Fully disallow mounted selections to be chosen in mounting menu
- [x] Prevent mounting to / on a NTFS volume (and other unsupported filesystems)
- [ ] Add support for more filesystem types (notably Btrfs)
- [ ] Add support for RAID in mounting & formatting options
- [ ] Add support for LUKS encryption in mounting & formatting options
